# Root project miscellaneous properties
sonar.projectKey=domrms_es2-sistemapedidos
sonar.projectName=ES2-SistemaPedidos
sonar.projectVersion=1.0.0

# Path to the project sources.
sonar.sources=src
sonar.exclusions=src/ES2-SistemaPedidos.FrontEnd/**/*

# Encoding of the source files
sonar.sourceEncoding=UTF-8
